name: Maven CD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Build with Maven
        run: mvn package

      - name: Get package version
        run: echo "packageVersion=$(mvn org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.version -q -DforceStdout)" > $GITHUB_ENV

      - name: Generate Javadoc
        run: mvn javadoc:javadoc

      - name: Bump version and push tag
        uses: negz/create-tag@v1
        with:
          version: v${{ env.packageVersion }}
          message: ${{ github.event.inputs.message }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release
        id: create_release
        uses: actions/create-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.packageVersion }}
          release_name: Release v${{ env.packageVersion }}
          body: |
            This is the first release of the project.
          draft: false
          prerelease: false

      - name: Upload Javadoc
        uses: actions/upload-artifact@v2
        with:
          name: javadoc
          path: target/site/apidocs/
