name: Maven CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Build with Maven
        run: mvn package

      - name: Run unit tests
        run: mvn test

      - name: Generate coverage report
        run: mvn jacoco:report

      - name: Generate JUnit XML test report
        run: mvn surefire-report:report-only
        
      - name: Run SonarCloud analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
          SONAR_ORGANIZATIONS_KEY: ${{ secrets.SONAR_ORGANIZATIONS_KEY }}
        run: mvn org.sonarsource.scanner.maven:sonar-maven-plugin:3.9.0.2155:sonar -Dsonar.projectKey=$SONAR_PROJECT_KEY -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=$SONAR_ORGANIZATIONS_KEY -Dsonar.java.coveragePlugin=jacoco -Dsonar.coverage.jacoco.xmlReportPaths=target/site/report/jacoco/jacoco.xml
        

      - name: Publish JUnit test report
        uses: actions/upload-artifact@v2
        with:
          name: junit-report
          path: target/surefire-reports/

      - name: Publish Jacoco Coverage Report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: target/site/jacoco/