name: Maven CD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Get package version
        run: echo "packageVersion=v$(mvn org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.version -q -DforceStdout)" > $GITHUB_ENV

      - name: Generate Javadoc
        run: mvn javadoc:javadoc

      - name: Create release
        id: create_release
        uses: actions/create-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.packageVersion }}
          release_name: Release ${{ env.packageVersion }}
          body: |
            This is the first release of the project.
          draft: false
          prerelease: false

      - name: Publish to Github Repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn deploy -P github-repository -DskipTests=true

      - name: Publish to Maven Central
        if: always()
        env:
          MAVEN_USER: ${{ secrets.MAVEN_CENTRAL_USER }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          MAVEN_SETTINGS_TEMPLATE: |
            <settings>
              <servers>
                <server>
                  <id>ossrh</id>
                  <username>$MAVEN_USER</username>
                  <password>$MAVEN_PASSWORD</password>
                </server>
              </servers>
            </settings>
        run: |
          echo "$MAVEN_SETTINGS_TEMPLATE" > settings_temp.xml
          envsubst < settings-temp.xml > settings.xml
          mvn deploy -P maven-central-repository -DskipTests=true
          rm settings.xml settlings-temp.xml

      - name: Upload Javadoc
        uses: actions/upload-artifact@v2
        with:
          name: javadoc
          path: target/site/apidocs/
